---
apiVersion: v1
kind: Service
metadata:
  name: as
spec:
  selector:
    app: as
  ports:
    - protocol: UDP
      port: 53533
      targetPort: 53533
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as
          image: andrexie/dns-as:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 53533
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: fs
spec:
  selector:
    app: fs
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: andrexie/dns-fs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: us
spec:
  selector:
    app: us
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
        - name: us
          image: andrexie/dns-us:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080